# =========================================================
# Configuration du serveur Fabrique
# =========================================================

mqtt.broker.url=tcp://localhost:1883
mqtt.client.id.prefix=fabrique-serveur
mqtt.qos=1
usine.capacity=0
